"""empty message

Revision ID: 202d7dd8dfaa
Revises: 888e5d646547
Create Date: 2023-08-11 17:05:11.582327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202d7dd8dfaa'
down_revision = '888e5d646547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('room_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_rooms')
    # ### end Alembic commands ###
